### ISSUE TITLE
Desktop keeps crashing after getting sync with mobile

### ISSUE THREAD

**Issue by churik** [status-im/status-desktop#11533]
# Bug Report

## Description

Originally issue https://github.com/status-im/status-go/pull/3743 and it is fixed and included to 1.24 on mobile side, but not on desktop side

## Steps to reproduce
Reproduced on certain multiaccounts after sync - desktop keeps crashing after login 

#### Expected behavior
no crash

### Additional Information

- Status desktop version: 0.13. RC 42
- Operating System: Mac Os Ventura 13.2.1
- Log: https://drive.google.com/file/d/1R19eIMwCK6tFKo-W14TygkBeZvf3kZza/view?usp=drive_link

**Comment by jrainville** [comment]
Cherry-picking this commit in the status-go release branch should fix it https://github.com/status-im/status-go/commit/3f5f87d1d1551b2570cb662fcd9cefc051096aa

**Comment by churik** [comment]
@jrainville 
still have issues with desktop after sync - it keeps crashing from time to time (as far as I saw mostly when the messages are fetching from offline for synced device)

Log: https://drive.google.com/file/d/1U4bptnJuGbt8aLhuRYASZjTRcRysZ5Fs/view?usp=sharing

Desktop version: [RC #46 ](https://ci.infra.status.im/job/status-desktop/job/release/job/release%252F0.13.x/46/)

**Comment by churik** [comment]
```
INF 2023-07-17 17:00:53.817+02:00 received                                   topics="signals-manager" tid=2110286 file=messages.nim:71 signal=messages.new messageID=0xa277b571163036c06488d979b6e4a727bfc2a0d865161d3651dce34ad44e0d8b
ERR 2023-07-17 17:00:53.817+02:00 unknown keypair type                       tid=2110286 file=keypair_dto.nim:35 kpType=
INF 2023-07-17 17:00:53.817+02:00 shutting down...                           topics="status-app" tid=2110286 file=nim_status_client.nim:157
INF 2023-07-17 17:00:53.817+02:00 logging out...                             topics="app-controller" tid=2110286 file=app_controller.nim:284
2023-07-17T17:00:53.856+0200	INFO	communities/manager.go:262	failed to request missing messages	{"error": "sql: database is closed"}
2023-07-17T17:00:53.856+0200	INFO	communities/manager.go:262	failed to get community settings	{"error": "sql: database is closed"}
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(193) nim_status_client
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/nim_status_client.nim(190) mainProc
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qguiapplication.nim(29) exec
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(49) qobjectCallback
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimqml/src/nimqml/private/qobject.nim(34) onSlotCalled
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/core/macros.nim(558) onSlotCalled
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/signals/signals_manager.nim(70) receiveSignal
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/signals/signals_manager.nim(46) processSignal
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/signals/signals_manager.nim(81) decode
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/src/app/core/signals/remote_signals/messages.nim(149) fromEvent
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim(824) toKeypairDto
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(38) failedAssertImpl
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/system/assertions.nim(28) raiseAssert
/Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/system/fatal.nim(54) sysFatal
Error: unhandled exception: /Users/jenkins/workspace/status-desktop/systems/macos/aarch64/package/vendor/nimbus-build-system/vendor/Nim/lib/pure/json.nim(824, 10) `node.kind == JArray` : items() can not iterate a JsonNode of kind JNull [AssertionDefect]
```

**Comment by igor-sirotin** [comment]
Stable reproduction steps:
1. Alice [mobile]: create new account
2. Alice [desktop]: local pairing from Alice [mobile]
3. Bob: send CR to Alice
4. Alice [desktop]: `unknown keypair type  tid=1540105 file=keypair_dto.nim:35 kpType=` (type is an empty string) and further crash on json parsing.

https://github.com/status-im/status-desktop/blob/f7e4b7fce157ac059ff9557d735539e02ad35f09/src/app_service/service/wallet_account/keypair_dto.nim#L35

After restarting the desktop app the crash comes there very soon with processing the same retrieved message.

I succeeded to hotfix this by skipping empty sync keypairs, but I think we also should fix this by not sending such messages in the first place. Dealing with this now.

Also checking now if same can be reproduced with desktop->desktop.

**Comment by igor-sirotin** [comment]
Hmmm, I can't reproduce this on desktop `master` branch. 
Will push a hotfix then and hope for the best 🙂

**Comment by igor-sirotin** [comment]
Fixed in https://github.com/status-im/status-go/pull/3773
