### ISSUE TITLE
Can not create an account on Windows 10

### ISSUE THREAD

**Issue by Samyoul** [status-im/status-desktop#12318]
# Bug Report

## Description

App version `0.13.3`
OS `Windows 10`

I can not create an account on Windows.

## Steps to reproduce

When trying to create an account the app redirects the user to the password confirmation page, however no matter the password used the application always reports that the password was incorrect.

At this point closing the app will cause a crash.

Attempting to open the account again gives the following error:

```
Login failed:
STATUS-GO ERROR
[METHODNAME:WAKUEXT_STARTMESSENGER,
CODE:-32603, MESSAGE:METHOD HANDLER
CRASHED ]
```

This issue is reproducible every time.

![image](https://github.com/status-im/status-desktop/assets/5702426/12eeb73c-9ebd-4755-b7e4-e726a8099ca5)
![image](https://github.com/status-im/status-desktop/assets/5702426/d926d772-41da-4919-afcc-7034df15815a)
![image](https://github.com/status-im/status-desktop/assets/5702426/87b5c07e-23ad-43e8-ba42-737810711be3)
![image](https://github.com/status-im/status-desktop/assets/5702426/0c3dca20-5af1-4888-b7c9-06f416157a7c)

#### Expected behavior

Using the correct password on the password confirmation page should confirm the account, and log the user into the application.

#### Actual behavior

The application does not confirm that password despite using the correct password.

### Additional Information

- Status desktop version: `0.13.3`
- Operating System: `Windows 10`

**Comment by jrainville** [comment]
That's a weird bug. Maybe you could wipe out the data folder. You can find it in `AppData/Local/Status`. Maybe the account database is corrupted?

Otherwise, we'll release 0.14 very soon, so maybe those issues are fixed there.

**Comment by alaibe** [comment]
![image](https://github.com/status-im/status-desktop/assets/491074/f2e6a33e-1e82-4c37-acbe-716850fb15fc)

Still happens to me on master, I was able to login fine til this error happens and I am now force to reset my db

**Comment by mprakhov** [comment]
closing as duplicate
https://github.com/status-im/status-desktop/issues/12831
