### ISSUE TITLE
Empty Wallet account screen when navigating from the Home page

### ISSUE THREAD

**Issue by jrainville** [status-im/status-desktop#18628]
# Bug Report

## Description

If you pin a wallet account and click on it, it does navigate to that account, but the view is empty. If you then switch to another account and back, the data is loaded successfully

https://github.com/user-attachments/assets/7e48797e-acad-4739-b00c-8144bf819161

## Steps to reproduce

0. Pin your wallet account in the Home page
1. Click the account on the bottom row

#### Expected behavior

Wallet account shows with its balance

#### Actual behavior

No balance

### Additional Information

- Status desktop version: 2.35.0 RC4
- Operating System: Ubuntu 22

**Comment by jrainville** [comment]
This one still happens in 2.38

**Comment by caybro** [comment]
Probably just another view navigation issue; I'd say solely within the WalletLayout

**Comment by caybro** [comment]
Already fixed in master

**Comment by jrainville** [comment]
I can still reproduce on master:

<img width="1302" height="798" alt="Image" src="https://github.com/user-attachments/assets/56a95a1a-d856-4ac7-ac01-df0f2ebbdbb9" />
