### ISSUE TITLE
Emoji icons for channels are broken in different places

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5158]
![Screenshot from 2022-03-24 12-48-11](https://user-images.githubusercontent.com/445106/159910157-e39aa5b5-42e7-4ba4-8015-905e85887a62.png)

**Comment by jrainville** [comment]
This should be fixed here: https://github.com/status-im/status-desktop/pull/5116

**Comment by iurimatias** [comment]
fixed in https://github.com/status-im/status-desktop/pull/5116

**Comment by PascalPrecht** [comment]
I've updated to latest `master` and still experience the same.
It's not the case for newly created channels though.

**Comment by PascalPrecht** [comment]
Perfect, will close this then.
