### ISSUE TITLE
Newly added contact doesn't show up in contact list when creating new chat

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#5275]
I've added an account as new contact from within a public chat:

Click on name -> View profile -> add to contacts

I then wanted to send that contact a message so I hit the button to create a new chat. I have a bunch of contacts, but the content I've just added doesn't show up here (looking for a contact named "test account 2"):
![Screenshot from 2022-03-30 16-10-12](https://user-images.githubusercontent.com/445106/160855369-b5da5239-b2ad-4d02-b69e-859efc33d5ff.png)

However, going to Settings -> Messaging -> Contacts, requests .. etc, the contact shows up:

![Screenshot from 2022-03-30 16-13-46](https://user-images.githubusercontent.com/445106/160855733-e7401eb0-3732-4ee4-83e5-a7c5ab570e36.png)

This should be consistent

**Comment by iurimatias** [comment]
should be fixed by PR https://github.com/status-im/status-desktop/pull/5171

**Comment by PascalPrecht** [comment]
Unfortunately it's not. This is still reproducible. Also looking at #5171, it in fact doesn't address this issue
