### ISSUE TITLE
UI elements in communities settings view appear too small

### ISSUE THREAD

**Issue by PascalPrecht** [status-im/status-desktop#7285]
As of latest `master` (`b2485603d`) this is what the communities settings view looks like:

![Screenshot from 2022-09-09 12-47-00](https://user-images.githubusercontent.com/445106/189336934-39434a0f-fb70-4196-af9b-9aa431297dc4.png)

Few things that seem wrong here:

1. All buttons appear smaller then other buttons in the app (probably a font-size thing)
2. The (letter)identicons for the community entries are too small

**Comment by alexandraB99** [comment]
@PascalPrecht this should be fixed in master, could you please check again and close?

**Comment by caybro** [comment]
@PascalPrecht can't reproduce in latest master

**Comment by PascalPrecht** [comment]
Looks like this is still reproducible on latest `master` (`15b67313b`)
![Screenshot from 2022-09-19 12-47-52](https://user-images.githubusercontent.com/445106/191001529-48800cb5-00dc-45e7-898a-e790d5079d3c.png)

**Comment by PascalPrecht** [comment]
Only thing that looks better is the "Import Community" button
