### ISSUE TITLE
messenger: clicking on a channel name doesn't work

### ISSUE THREAD

**Issue by caybro** [status-im/status-desktop#9561]
# Bug Report

It seems like a regression but clicking on a channel name (e.g. `#intros` here) in the chat no longer takes the user to the target. It fails with:

```
ERR 2023-02-16 10:22:17.137+01:00 chat-view unexisting item id: topics="chat-section-module" tid=144186 file=module.nim:396 itemId=256c3318-342f-403f-b4ec-648cdeb26245 methodName=activeItemSet
```

![image](https://user-images.githubusercontent.com/5377645/219322552-fe072f2e-c97c-4597-b131-6b6365e29d5c.png)

### Additional Information

- Status desktop version: linux
- Operating System: master (ed9e7822629ca3977436db63cce0dfc3092819f1)

**Comment by caybro** [comment]
cc @jrainville @0x-r4bbit

**Comment by jrainville** [comment]
Must have been fixed lately. I cannot reproduce on master.

**Comment by caybro** [comment]
Still broken for me on master:

Click on `#mobile` here:
![image](https://user-images.githubusercontent.com/5377645/222682412-4f2c62fc-f346-4686-824e-98742ea9eb17.png)

Leads to empty screen:
![image](https://user-images.githubusercontent.com/5377645/222682486-1841538a-9998-4831-a486-7e1603bd3468.png)

Console log:
```
ERR 2023-03-03 10:23:03.283+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
ERR 2023-03-03 10:23:03.283+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
ERR 2023-03-03 10:23:03.285+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
ERR 2023-03-03 10:23:03.287+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
```

**Comment by caybro** [comment]
More logs:

```
ERR 2023-03-03 10:25:14.457+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
ERR 2023-03-03 10:25:14.458+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
ERR 2023-03-03 10:25:14.550+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
Warning: qrc:/app/AppLayouts/Chat/views/ChatContentView.qml:44: TypeError: Cannot read property 'usersModule' of undefined (qrc:/app/AppLayouts/Chat/views/ChatContentView.qml:44, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatMessagesView.qml:120:9: Unable to assign [undefined] to bool (qrc:/app/AppLayouts/Chat/views/ChatMessagesView.qml:120, )
Warning: qrc:/app/AppLayouts/Chat/views/ChatMessagesView.qml:51: TypeError: Cannot read property 'chatDetails' of undefined (qrc:/app/AppLayouts/Chat/views/ChatMessagesView.qml:51, )
ERR 2023-03-03 10:25:14.557+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
ERR 2023-03-03 10:25:14.558+01:00 unexisting chat key:                       topics="chat-section-module" tid=9080 file=module.nim:405 chatId=27f7dddb-5d12-42a0-9f4f-2b2329ab1544 methodName=getChatContentModule
```

**Comment by caybro** [comment]
cc @jrainville can you reproduce this one?
